Autocomplete statements #1066
GovReady/govready-q pull request #1111
Opened 2020-11-19 14:04 UTC by davidpofo

2020-11-20 00:31 UTC, bama4 commented on controls/models.py
> +        from copy import deepcopy
Unless you are doing a conditional import, you may want to consider placing all imports at the top of the file

2020-11-20 00:31 UTC, bama4 commented on controls/models.py
> +        from copy import deepcopy
Same here (see import comment)

2020-11-22 19:58 UTC, gregelin requested changes
Please do not make any changes to `autocomplete_statements_#1066`. I am in the process of synchronizing 3 branches: 
- autocomplete_statements_#1066
- ge/reuse-0903
- automated-tests-statements

2020-11-23 02:12 UTC, gregelin commented
The following three branches are currently synchronized as of 18934669:

- `autocomplete_statements_#1066`
- `ge/reuse-0903`
- `automated-tests-statements`

2020-11-23 03:40 UTC, gregelin commented
Still need to be addressed: Making sure solution works for statements associated with parts. 

Reproducing error:
1. Create a control statement for a component and associated statement with a control part
2. Create a second control statement for a component and associated statement with a different control part
3. Change the local control statement for one of the parts.
4. Update the certified statement for the changed control.
5. ERROR: the updated certified statement is updated for the control statements for both parts of the control.

What should happened is the statements for different control parts are treated differently.

2020-11-23 17:31 UTC, davidpofo commented on CHANGELOG.md
> +>>>>>>> master
Left over from fixing conflicts I am guessing

2020-11-23 17:31 UTC, davidpofo commented on controls/tests.py
> +    def create_test_statement(self, sid, sid_class, body, statement_type, status):
This was actually from an early iteration it is not used in this set of tests.

2020-12-01 18:06 UTC, omarabed15 requested changes

2020-12-02 21:03 UTC, davidpofo commented on controls/tests.py
> +        self.navigateToPage("/systems/1/controls/catalogs/NIST_SP-800-53_rev4/control/ac-3")
We actually need to hit line 497 to assign a baseline to the system we are on(system 1). I'll remove 495 as its not needed thanks for pointing that out!

2020-12-02 21:04 UTC, davidpofo commented on controls/utilities.py
> +        catalogkey = split_key_list[0] + "-800-" + split_key_list[1]
No this is consistent as it refers to the sid class. Check out the class Catalogs.

2020-12-02 21:09 UTC, davidpofo commented on controls/utilities.py
> +        catalogkey = 'NIST_SP-800-53_rev4'
Not sure if that is necessary as this is already a utility function to provide a default catalog key when empty. No opinion on the default though just needed one of them for an empty edgecase.  @gregelin is this sid_class appropriate as a default?

2020-12-04 01:47 UTC, merged